--- #YAML:1.0
name:               Chemistry-File-SMILES
version:            0.47
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Chemistry::Bond::Find:  0.21
    Chemistry::Canonicalize:  0.10
    Chemistry::Mol:       0.30
    Chemistry::Ring:      0.15
    List::Util:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
